In [3]:
import pandas as pd
import numpy as np

### Difference between reading excel and csv
Note the time difference

In [4]:
df = pd.read_excel('Data\\main_dataset.xlsx')

c:\Users\swift\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)


In [30]:
df = pd.read_csv('Data\\main_dataset.csv')

If you are using colab, or you are facing any difficulties with reading the csv, run the cell below instead

In [ ]:
# df = pd.read_csv('https://raw.githubusercontent.com/Addyzee/RPSc/master/Pregancy_Outcomes/Data/main_dataset.csv')

### The data

This data is obtained from a case study [here](https://drive.google.com/file/d/1zG-NJVOdMh5ex1T8k3Fn8TL1xpLoWEjH/view?usp=drive_link) . It includes the outcomes of pregnancies from some health facilities in Kenya and Uganda. You can go through the study and the [data dictionary](https://docs.google.com/spreadsheets/d/1ySK_tZTUpGNjIdBpi3joYvlIRSjhEsg0/edit?usp=drive_link&ouid=106123374821591906756&rtpof=true&sd=true) to gain more understanding. You can also go through the [data dictionary](https://docs.google.com/spreadsheets/d/1ySK_tZTUpGNjIdBpi3joYvlIRSjhEsg0/edit?usp=drive_link&ouid=106123374821591906756&rtpof=true&sd=true) and check the [readme](https://raw.githubusercontent.com/Addyzee/RPSc/master/Pregancy_Outcomes/Data/readme.txt) that was generated from this data.<br>
Note that for today's class, we have renamed the columns to more self explanatory column names. This is what the next few cells of code do. We use their definitions from the data dictionary to make it easier for us to understand what they mean. We can then rename them depending on what we want to call them. This is what the next few cells of code do. You can browse through them quickly, then skip to the data assessment section below.

In [31]:
# current columns are not very intuitive for us to understand. We will rename them
df.columns

Index(['id', 'country', 'facility_coded', 'referral_in', 'apgar_1', 'apgar_5',
       'sex', 'baby_discharge_status', 'multiple', 'bba', 'doc_abortion',
       'doc_iufd', 'record_type', 'mothers_age_cat', 'c_mother_status',
       'c_cat_ga', 'c_cat_bw', 'c_mode_of_delivery', 'quarter',
       'c_baby_status', 'c_birth_outcome', 'c_birth_weight_g2'],
      dtype='object')

In [28]:
# pick the defiitions used by the authors in the data dictionary
data_dictionary = pd.read_excel('Data/datadictionary.xlsx')
print(list(data_dictionary['Unnamed: 1']))

['Content', 'country', 'Health  Facility Code  1-23', 'Was the mother referred into facility prior devliery? (First Contact/Follow-up Form)/ Referred In (MAT Reg) ', "Infant's apgar score at 1  minute", "Infant's apgar score at 5 minutes", 'Sex of infant at birth', "Baby's Status at Discharge ", 'Multiple births', 'record  contains designation  that baby  was born  before  arrival at the  facility', 'record  contains documentation  that the pregnancy  outcome was a  spontneous abortion', 'record  conains designation that the fetal outcome was intrauterine fetal demise', 'Designates whether record was considered a birth or not', "Mother's age", "Mother's Discharge Status ", 'Categorical GA  groups', 'Categorical BW groups', 'Mode of Delivery ', 'coded designation of quarters to enable data aggregation', "Baby's Status at Delivery ", '<none>', 'Birthweight in  grams']


In [32]:
# rename from original column names to the ones in the data dictionary
new_cols = ['country', 'Health  Facility Code  1-23', 'Was the mother referred into facility prior devliery? (First Contact/Follow-up Form)/ Referred In (MAT Reg) ', "Infant's apgar score at 1  minute", "Infant's apgar score at 5 minutes", 'Sex of infant at birth', "Baby's Status at Discharge ", 'Multiple births', 'record  contains designation  that baby  was born  before  arrival at the  facility', 'record  contains documentation  that the pregnancy  outcome was a  spontneous abortion',
            'record  conains designation that the fetal outcome was intrauterine fetal demise', 'Designates whether record was considered a birth or not', "Mother's age", "Mother's Discharge Status ", 'Categorical GA  groups', 'Categorical BW groups', 'Mode of Delivery ', 'coded designation of quarters to enable data aggregation', "Baby's Status at Delivery ", 'Birth status', 'Birthweight in  grams']
df.rename(columns ={df.columns[1:][i] : new_cols[i] for i in range(len(new_cols))},inplace=True)

In [33]:
# These are the new column names
df.columns

Index(['id', 'country', 'Health  Facility Code  1-23',
       'Was the mother referred into facility prior devliery? (First Contact/Follow-up Form)/ Referred In (MAT Reg) ',
       'Infant's apgar score at 1  minute',
       'Infant's apgar score at 5 minutes', 'Sex of infant at birth',
       'Baby's Status at Discharge ', 'Multiple births',
       'record  contains designation  that baby  was born  before  arrival at the  facility',
       'record  contains documentation  that the pregnancy  outcome was a  spontneous abortion',
       'record  conains designation that the fetal outcome was intrauterine fetal demise',
       'Designates whether record was considered a birth or not',
       'Mother's age', 'Mother's Discharge Status ', 'Categorical GA  groups',
       'Categorical BW groups', 'Mode of Delivery ',
       'coded designation of quarters to enable data aggregation',
       'Baby's Status at Delivery ', 'Birth status', 'Birthweight in  grams'],
      dtype='object')

Optional-- You can use the next two cells to check the difference between writing to a csv, and writing to an excel file. Note the time taken by each. 

In [ ]:
df.to_csv('main_dataset_renamed.csv',index=0)

In [26]:
df.to_excel('main_dataset_renamed.xlsx',index=0)

### Data Assessment

#### Understanding our data more

For the questions below, you can start answering questions like what our sample size was, and which variables were collected in this data.<br>
Checkout functions like `.shape()`,`.info()`, `head()`, `tail()`, among others you have already seen. You can use the [cheatsheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf) too.

What do the first ten rows of your data look like?

What do the last ten look like?

Can you randomly display 10 rows from the data?

Great! What do you think each record represents? Have you noted any data issues already? <br>
How many records do we have in the dataset? <br>
*Hint: You can use one of the functions mentioned above.*

How many columns do we have in the dataset?<br>
*Also one of the functions mentioned above*

What data types do you have in your data?

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61018 entries, 0 to 61017
Data columns (total 22 columns):
 #   Column                                                                                                        Non-Null Count  Dtype  
---  ------                                                                                                        --------------  -----  
 0   id                                                                                                            61018 non-null  int64  
 1   country                                                                                                       61018 non-null  int64  
 2   Health  Facility Code  1-23                                                                                   61018 non-null  object 
 3   Was the mother referred into facility prior devliery? (First Contact/Follow-up Form)/ Referred In (MAT Reg)   36636 non-null  object 
 4   Infant's apgar score at 1  minute                   

What do each of the `Dtype`s mean? What do you think `object` means as opposed to `float`? Do you think there are other data types we could have to replace the `object` `Dtype`?

#### Splitting the data

For this session, we will focus on cleaning the first 15 columns, and for your assignment, you can work on the remaining columns. Let's start by getting subsets of our data.

In [43]:
df.columns[:15]

Index(['id', 'country', 'Health  Facility Code  1-23',
       'Was the mother referred into facility prior devliery? (First Contact/Follow-up Form)/ Referred In (MAT Reg) ',
       'Infant's apgar score at 1  minute',
       'Infant's apgar score at 5 minutes', 'Sex of infant at birth',
       'Baby's Status at Discharge ', 'Multiple births',
       'record  contains designation  that baby  was born  before  arrival at the  facility',
       'record  contains documentation  that the pregnancy  outcome was a  spontneous abortion',
       'record  conains designation that the fetal outcome was intrauterine fetal demise',
       'Designates whether record was considered a birth or not',
       'Mother's age', 'Mother's Discharge Status '],
      dtype='object')

In [38]:
# Do you remember the `loc()` function? What do you think this code means? 
# You can refer to the cheatsheet or pandas documentation of you don't remember
df.loc[:,:"Mother's Discharge Status "]

id  country Health  Facility Code  1-23  \
0      162230        2                      HF0004   
1      127964        2                      HF0005   
2      148113        2                      HF0006   
3       95858        1                       HF014   
4      206414        1                       HF007   
...       ...      ...                         ...   
61013  203864        1                       HF023   
61014  203873        1                       HF023   
61015  203886        1                       HF023   
61016  205920        1                       HF023   
61017  205938        1                       HF023   

      Was the mother referred into facility prior devliery? (First Contact/Follow-up Form)/ Referred In (MAT Reg)   \
0                                                      1                                                             
1                                                    NaN                                                             
2                                                      0                                                             
3                                                    NaN                                                             
4                                                    NaN                                                             
...                                                  ...                                                             
61013                                                NaN                                                             
61014                                                NaN                                                             
61015                                                NaN                                                             
61016                                                NaN                                                             
61017                                                NaN                                                             

       Infant's apgar score at 1  minute  Infant's apgar score at 5 minutes  \
0                                    7.0                                9.0   
1                                    NaN                                NaN   
2                                    NaN                                NaN   
3                                   10.0                               10.0   
4                                    9.0                               10.0   
...                                  ...                                ...   
61013                                9.0                               10.0   
61014                                9.0                               10.0   
61015                               10.0                               10.0   
61016                                NaN                                NaN   
61017                                4.0                                4.0   

      Sex of infant at birth Baby's Status at Discharge   Multiple births  \
0                       Male                         NaN              1.0   
1                        NaN                         NaN              1.0   
2                        NaN                         NaN              1.0   
3                       Male                       Alive              NaN   
4                       Male                       Alive              1.0   
...                      ...                         ...              ...   
61013                 Female                       Alive              1.0   
61014                   Male                       Alive              1.0   
61015                 Female                       Alive              1.0   
61016                    NaN                         NaN              1.0   
61017                   Male                       Alive              1.0   

       record  contains designation  that baby  was born  before  arriv

In [44]:
# Can you similarly use the loc function to get all columns until the column `Multiple births`?


In [ ]:
# What about getting the first 200 records from all columns? 


In [46]:
# Let's store the first 15 columns in a subset of our data
df_15 = df.loc[:,:"Mother's Discharge Status "]

#### Data Quality and Tidiness

Since we don't know which columns may have any issues, we will slowly go over each column asking ourselves questions, based on what we know to be true from the study. For example, we know that this study was conducted in two countries. Is this reflected in the data?

In [55]:
df_15.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61018 entries, 0 to 61017
Data columns (total 15 columns):
 #   Column                                                                                                        Non-Null Count  Dtype  
---  ------                                                                                                        --------------  -----  
 0   id                                                                                                            61018 non-null  int64  
 1   country                                                                                                       61018 non-null  int64  
 2   Health  Facility Code  1-23                                                                                   61018 non-null  object 
 3   Was the mother referred into facility prior devliery? (First Contact/Follow-up Form)/ Referred In (MAT Reg)   36636 non-null  object 
 4   Infant's apgar score at 1  minute                   

How many countries are included in this dataset? How are they represented in this data?
*You can try finding the `unique()` countries*

What is the number of health facilities in the dataset? Is this consistent with what we expect from the study?

23

Now to the third column. This column asks the question 'Was the mother referred into the facility from another health facility before delivery?'. This happens a lot of times in hospitals. <br>
Before looking at the data, how many answers do you think there can be to this question?<br>

In [67]:
df_15['Was the mother referred into facility prior devliery? (First Contact/Follow-up Form)/ Referred In (MAT Reg) '].unique()

array(['1', nan, '0', 'yes'], dtype=object)

In a simple real world situation, there can only be three answers. **Yes**, **No**, and **I don't know**. In simpler cases, it would just be **Yes** and **No**.<br>
This means that the maximum number of values that this column should have is three. Is this the case from our data? What do you think each value from our data means?

Have we already spotted a data quality issue? Which one do you think this is?

In [69]:
df_15['Was the mother referred into facility prior devliery? (First Contact/Follow-up Form)/ Referred In (MAT Reg) '].value_counts()

0      32302
1       4331
yes        3
Name: Was the mother referred into facility prior devliery? (First Contact/Follow-up Form)/ Referred In (MAT Reg) , dtype: int64

What is the data quality issue and how could we fix it?<br>
**Answer here:**

The next two columns deal with [apgar score](https://www.healthline.com/health/apgar-score#apgar-rubric). This is generally a scale from 0 - 10 that you can think of as a way to represent a baby's health. It is recorded at the first minute after birth, and five minutes after birth.<br>
Now, this is really domain specific information, but before looking at the data, what values would you argue are expected when answering such a question?

What does the data say?

In [71]:
df['Infant\'s apgar score at 1  minute'].unique()

array([ 7., nan, 10.,  9.,  6.,  8.,  4.,  0.,  5.,  2.,  3.,  1.])

In [75]:
df['Infant\'s apgar score at 5 minutes'].unique()

array([ 9., nan, 10.,  8.,  4.,  0.,  7.,  6.,  5.,  1.,  3.,  2.])

Any data quality issues here? <br>
What about data tidiness issues?<br>
**Answer here:**

The next column is `Sex of infant at birth`. What do you expect as responses here?

In [78]:
# What does the data say?


array(['Male', nan, 'Female', 'Not_indicated'], dtype=object)

Any issues between expectations and data?

#### Assignment 1
Do you see the questions we are asking ourselves before identifying issues with our data? Knowing what to expect, and confirming whether that is what we have in the data is very crucial in data cleaning. <br>
Your first assignment is to contine with this trend for the remaining columns. We will skip into data cleaning for issues identified, but be sure to go through the remaining data.

#### Assignment 2:: Brainstorm
Think about the data tidiness issues. Are there any different ways you could have changed this data to best suit, not only data tidiness, but also the purpose it is meant to serve? What do you think is the cause of any issues you come up with?

### Data cleaning

We may not have gone deep into how to fix the data cleaning issues, but it's just applying the functions that we have already learned. One good first step to always cover is to rename all your columns in a way that allows you to easily manipulate your data. We should have done this at the very beginning, but we had not really understood our data well.For this notebook, I will rename the columns slowly as I deal with each one.<br>
For this case, we will only focus on **data quality** issues. This dataset breaks plenty rules in data tidiness, but before we fix those, let's work on the data quality issues.

#### referral

The first issue we identified was in the column `'Was the mother referred into facility prior devliery? (First Contact/Follow-up Form)/ Referred In (MAT Reg) '`. <br>
In this column, we expect the responses to be either `yes`, `no`, or `nan`(which represents that we didn't find this data). From the data, we have `0` representing the `no` responses, `1` representing the `yes`, but we also have 3 values that also read `yes`.<br> 
Since we expect only `1`s and `0`s, the appearance of `yes` appears to be incorrect data, in terms of data representation.<br>
We would fix this issue by replacing the `yes`s with `1`s

We'll begin with renaming the column so as to work with it better

In [83]:
df_15.rename(columns={
             'Was the mother referred into facility prior devliery? (First Contact/Follow-up Form)/ Referred In (MAT Reg) ': 'referral_in'}, inplace=True)

In [87]:
# then now, let's find where those 'yes's appear using the `isin()` function that we learnt
df_15.referral_in.isin(['yes'])

0        False
1        False
2        False
3        False
4        False
         ...  
61013    False
61014    False
61015    False
61016    False
61017    False
Name: referral_in, Length: 61018, dtype: bool

The response above is not so helpful. Remember how used square brackets to find the exact locations from boolean responses?

In [91]:
df_15[df_15.referral_in.isin(['yes'])]

id  country Health  Facility Code  1-23 referral_in  \
3421   76216        2                      HF0006         yes   
32352  76220        2                      HF0006         yes   
39129  76217        2                      HF0006         yes   

       Infant's apgar score at 1  minute  Infant's apgar score at 5 minutes  \
3421                                 NaN                                NaN   
32352                                NaN                                NaN   
39129                                NaN                                NaN   

      Sex of infant at birth Baby's Status at Discharge   Multiple births  \
3421                     NaN                         NaN              1.0   
32352                    NaN                         NaN              1.0   
39129                    NaN                         NaN              1.0   

       record  contains designation  that baby  was born  before  arrival at the  facility  \
3421                                                   0                                     
32352                                                  0                                     
39129                                                  0                                     

       record  contains documentation  that the pregnancy  outcome was a  spontneous abortion  \
3421                                                   0                                        
32352                                                  0                                        
39129                                                  0                                        

       record  conains designation that the fetal outcome was intrauterine fetal demise  \
3421                                                 NaN                                  
32352                                                NaN                                  
39129                                                NaN                                  

      Designates whether record was considered a birth or not Mother's age  \
3421                                      Discharge_Preg               ≤19   
32352                                     Discharge_Preg             20-24   
39129                                     Discharge_Preg             25-29   

      Mother's Discharge Status   
3421            Discharged_Alive  
32352           Discharged_Alive  
39129           Discharged_Alive

Great! We can see that the indices `3421`, `32352`, and `39129` have `yes`s instead of `1`s. Now let's fix this. There are tons of ways to do this. We'll look at 2. Using conditions and the [loc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html) method, and using the [replace](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.replace.html) function. 

##### `replace()` method

This is fairly straight forward, just like the `replace` method in strings

In [116]:
df_15.referral_in.replace({'yes':1})

0          1
1        NaN
2          0
3        NaN
4        NaN
        ... 
61013    NaN
61014    NaN
61015    NaN
61016    NaN
61017    NaN
Name: referral_in, Length: 61018, dtype: object

Again, the input is not so intuitive, especially because we have a lot of data. Let's look at the specific sections that we want to change using their indices

In [115]:
df_15.referral_in.replace({'yes':1})[[3421, 32352, 39129]]

3421     1
32352    1
39129    1
Name: referral_in, dtype: object

The output does not give us the whole dataframe, but we can see that the indices have been changed. <br>Like some other functions in `pandas`, `replace` requires you add the `inplace` argument to make changes to the original dataframe.

In [ ]:
df_15.referral_in.replace({'yes':1}, inplace=True)

In [107]:

df_15.loc[[3421, 32352, 39129]].replace({'yes':1})

id  country Health  Facility Code  1-23  referral_in  \
3421   76216        2                      HF0006            1   
32352  76220        2                      HF0006            1   
39129  76217        2                      HF0006            1   

       Infant's apgar score at 1  minute  Infant's apgar score at 5 minutes  \
3421                                 NaN                                NaN   
32352                                NaN                                NaN   
39129                                NaN                                NaN   

       Sex of infant at birth  Baby's Status at Discharge   Multiple births  \
3421                      NaN                          NaN              1.0   
32352                     NaN                          NaN              1.0   
39129                     NaN                          NaN              1.0   

       record  contains designation  that baby  was born  before  arrival at the  facility  \
3421                                                   0                                     
32352                                                  0                                     
39129                                                  0                                     

       record  contains documentation  that the pregnancy  outcome was a  spontneous abortion  \
3421                                                   0                                        
32352                                                  0                                        
39129                                                  0                                        

       record  conains designation that the fetal outcome was intrauterine fetal demise  \
3421                                                 NaN                                  
32352                                                NaN                                  
39129                                                NaN                                  

      Designates whether record was considered a birth or not Mother's age  \
3421                                      Discharge_Preg               ≤19   
32352                                     Discharge_Preg             20-24   
39129                                     Discharge_Preg             25-29   

      Mother's Discharge Status   
3421            Discharged_Alive  
32352           Discharged_Alive  
39129           Discharged_Alive

##### Conditions + the `loc` method

In [138]:
# run this cell to revert the changes above
df_15 = df.loc[:,:"Mother's Discharge Status "]
df_15.rename(columns={
             'Was the mother referred into facility prior devliery? (First Contact/Follow-up Form)/ Referred In (MAT Reg) ': 'referral_in'}, inplace=True)


We already saw conditions in the intro to python notebooks. Remember `>`,`<`, and `==`. Even the `isin` function runs based on a certain condition. We are looking for plces where `referral_in` == `yes`.

In [139]:
df_15.referral_in == 'yes'

0        False
1        False
2        False
3        False
4        False
         ...  
61013    False
61014    False
61015    False
61016    False
61017    False
Name: referral_in, Length: 61018, dtype: bool

Then our neat trick...

In [140]:
df_15[df_15.referral_in == 'yes']

id  country Health  Facility Code  1-23 referral_in  \
3421   76216        2                      HF0006         yes   
32352  76220        2                      HF0006         yes   
39129  76217        2                      HF0006         yes   

       Infant's apgar score at 1  minute  Infant's apgar score at 5 minutes  \
3421                                 NaN                                NaN   
32352                                NaN                                NaN   
39129                                NaN                                NaN   

      Sex of infant at birth Baby's Status at Discharge   Multiple births  \
3421                     NaN                         NaN              1.0   
32352                    NaN                         NaN              1.0   
39129                    NaN                         NaN              1.0   

       record  contains designation  that baby  was born  before  arrival at the  facility  \
3421                                                   0                                     
32352                                                  0                                     
39129                                                  0                                     

       record  contains documentation  that the pregnancy  outcome was a  spontneous abortion  \
3421                                                   0                                        
32352                                                  0                                        
39129                                                  0                                        

       record  conains designation that the fetal outcome was intrauterine fetal demise  \
3421                                                 NaN                                  
32352                                                NaN                                  
39129                                                NaN                                  

      Designates whether record was considered a birth or not Mother's age  \
3421                                      Discharge_Preg               ≤19   
32352                                     Discharge_Preg             20-24   
39129                                     Discharge_Preg             25-29   

      Mother's Discharge Status   
3421            Discharged_Alive  
32352           Discharged_Alive  
39129           Discharged_Alive

Just like the `isin` function. One difference is that with the `isin`, you have to feed a list as the argument. This is why we use square brackets when using `isin`. Let's now add the `loc` method.

In [141]:
df_15.loc[df_15.referral_in == 'yes', 'referral_in'] = 1

The above cell makes all changes we want. Checkout [documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html) for the loc method if it still looks unfamiliar. 
<br>
However, here is how you can think of it:
<br>
Use a condition to get the section where you want to make your changes: `df_15.referral_in == 'yes'`<br>
The loc function just allows us to add an extra argument after feeding the condition: where you want to make that change(which column): `df.loc[..., 'referral_in']`, and what the change is(change whatever is in the condition to 1): `df.loc[...] = 1`<br>


In [142]:
# Now when we try to find where the `yes` are, there are none
df_15[df_15.referral_in == 'yes']

Empty DataFrame
Columns: [id, country, Health  Facility Code  1-23, referral_in, Infant's apgar score at 1  minute, Infant's apgar score at 5 minutes, Sex of infant at birth, Baby's Status at Discharge , Multiple births, record  contains designation  that baby  was born  before  arrival at the  facility, record  contains documentation  that the pregnancy  outcome was a  spontneous abortion, record  conains designation that the fetal outcome was intrauterine fetal demise, Designates whether record was considered a birth or not, Mother's age, Mother's Discharge Status ]
Index: []

#### sex

Greaat! You can use whichever method to clean the data. Can you make similar changes to the next column: `Sex of infant at birth`? There are some unneccesary values within.

In [134]:
df_15['Sex of infant at birth'].value_counts(dropna= False)

Male             24251
Female           22734
NaN              13661
Not_indicated      372
Name: Sex of infant at birth, dtype: int64

#### Assignment 3
Continue with fixing other data quality issues in this dataset before going to data tidiness.